# Copyright (C) 2026 The LineageOS Project
# SPDX-License-Identifier: Apache-2.0

# This file is generated by setup-makefiles.py

LOCAL_PATH := $(call my-dir)

# Proprietary blobs are installed via PRODUCT_COPY_FILES in a26x-vendor.mk
# This Android.mk exists to satisfy build system requirements

