#!/bin/bash
#
# Copyright (C) 2016 The CyanogenMod Project
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

set -e

DEVICE=a26x
VENDOR=samsung

INITIAL_COPYRIGHT_YEAR=2026

OUTFD=

echo() {
    if [ -n "$OUTFD" ]; then
        printf "ui_print %s\nui_print\n" "$1" > /proc/self/fd/"$OUTFD"
    else
        command echo "$1"
    fi
}

usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  -d, --device DEVICE    Target device codename (default: $DEVICE)"
    echo "  -o, --output           Output makefile to stdout"
    echo "  -h, --help             Display this help message"
    exit 1
}

parse_options() {
    while [ "$#" -gt 0 ]; do
        case "$1" in
            -d|--device)
                DEVICE="$2"
                shift 2
                ;;
            -o|--output)
                OUTPUT=true
                shift
                ;;
            -h|--help)
                usage
                ;;
            *)
                echo "Unknown option: $1"
                usage
                ;;
        esac
    done
}

write_headers() {
    echo "#"
    echo "# Copyright (C) $INITIAL_COPYRIGHT_YEAR The LineageOS Project"
    echo "#"
    echo "# SPDX-License-Identifier: Apache-2.0"
    echo "#"
    echo ""
    echo "# This file is generated by setup-makefiles.sh"
    echo ""
}

write_makefile_header() {
    cat <<'EOF'
LOCAL_PATH := $(call my-dir)

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/a26x

EOF
}

process_vendor_files() {
    local prop_dir="proprietary/vendor"
    local first=true
    
    if [ ! -d "$prop_dir" ]; then
        return
    fi
    
    echo "# Vendor files"
    echo "PRODUCT_COPY_FILES += \\"
    
    find "$prop_dir" -type f | sort | while read -r file; do
        local rel_path="${file#$prop_dir/}"
        printf '    $(LOCAL_PATH)/proprietary/vendor/%s:$(TARGET_COPY_OUT_VENDOR)/%s:samsung \\\n' "$rel_path" "$rel_path"
    done
    
    sed -i '$ s/ \\$//'
    echo ""
    echo ""
}

process_system_files() {
    local prop_dir="proprietary/system"
    
    if [ ! -d "$prop_dir" ]; then
        return
    fi
    
    echo "# System files"
    echo "PRODUCT_COPY_FILES += \\"
    
    find "$prop_dir" -type f | sort | while read -r file; do
        local rel_path="${file#$prop_dir/}"
        printf '    $(LOCAL_PATH)/proprietary/system/%s:$(TARGET_COPY_OUT_SYSTEM)/%s:samsung \\\n' "$rel_path" "$rel_path"
    done
    
    sed -i '$ s/ \\$//'
    echo ""
}

generate_makefile() {
    local output_file="${1:-$DEVICE-vendor.mk}"
    local tmp_file=$(mktemp)
    
    write_headers > "$tmp_file"
    write_makefile_header >> "$tmp_file"
    
    if [ -d "proprietary/vendor" ]; then
        echo "# Vendor files" >> "$tmp_file"
        echo "PRODUCT_COPY_FILES += \\" >> "$tmp_file"
        find proprietary/vendor -type f | sort | while read -r file; do
            local rel_path="${file#proprietary/vendor/}"
            printf '    $(LOCAL_PATH)/proprietary/vendor/%s:$(TARGET_COPY_OUT_VENDOR)/%s:samsung \\\n' "$rel_path" "$rel_path" >> "$tmp_file"
        done
        sed -i '$ s/ \\$//' "$tmp_file"
        echo "" >> "$tmp_file"
        echo "" >> "$tmp_file"
    fi
    
    if [ -d "proprietary/system" ]; then
        echo "# System files" >> "$tmp_file"
        echo "PRODUCT_COPY_FILES += \\" >> "$tmp_file"
        find proprietary/system -type f | sort | while read -r file; do
            local rel_path="${file#proprietary/system/}"
            printf '    $(LOCAL_PATH)/proprietary/system/%s:$(TARGET_COPY_OUT_SYSTEM)/%s:samsung \\\n' "$rel_path" "$rel_path" >> "$tmp_file"
        done
        sed -i '$ s/ \\$//' "$tmp_file"
        echo "" >> "$tmp_file"
    fi
    
    mv "$tmp_file" "$output_file"
}

main() {
    parse_options "$@"
    
    echo "Generating makefiles for $DEVICE"
    echo "=================================="
    
    if [ "$OUTPUT" = true ]; then
        write_headers
        write_makefile_header
        if [ -d "proprietary/vendor" ]; then
            echo "# Vendor files"
            echo "PRODUCT_COPY_FILES += \\"
            find proprietary/vendor -type f | sort | while read -r file; do
                rel_path="${file#proprietary/vendor/}"
                printf '    $(LOCAL_PATH)/proprietary/vendor/%s:$(TARGET_COPY_OUT_VENDOR)/%s:samsung \\\n' "$rel_path" "$rel_path"
            done | sed '$ s/ \\$//'
            echo ""
            echo ""
        fi
        if [ -d "proprietary/system" ]; then
            echo "# System files"
            echo "PRODUCT_COPY_FILES += \\"
            find proprietary/system -type f | sort | while read -r file; do
                rel_path="${file#proprietary/system/}"
                printf '    $(LOCAL_PATH)/proprietary/system/%s:$(TARGET_COPY_OUT_SYSTEM)/%s:samsung \\\n' "$rel_path" "$rel_path"
            done | sed '$ s/ \\$//'
            echo ""
        fi
    else
        generate_makefile "$DEVICE-vendor.mk"
        
        local file_count=$(find proprietary -type f 2>/dev/null | wc -l)
        echo ""
        echo "Generated: $DEVICE-vendor.mk ($file_count files)"
    fi
}

main "$@"
